### ISSUE TITLE
Unable to Label  Images Uploaded from PC

### ISSUE THREAD

**Issue by tagoreji** [HumanSignal/label-studio#3490]
**page URL** : http://localhost:8080/projects/4/undefined$

**Displayed Error**

There was an issue loading URL from $undefined$ value

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)

Technical description:
URL: [undefined$]

**Comment by tagoreji** [comment]
![label_error](https://user-images.githubusercontent.com/72594944/209534660-8e4e2ee2-5815-424c-96e8-43c94035be37.jpg)

**Comment by makseq** [comment]
@tagoreji do you use valueType="url" in your Image tag?

**Comment by ucas010** [comment]
I have the same problem

```
There was an issue loading URL from $image value

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)
Technical description:
URL:
```
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/50656998/223332707-5fb77157-53f5-448d-a32e-1ce6a637e541.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/50656998/223332804-473f1efb-f5bc-4d49-a3bf-9fce92d3c0a1.png">

**Comment by makseq** [comment]
1. Please show your labeling config
2. Show a sample task data

**Comment by oamm** [comment]
Hi, I have the same issue, but i figured out something the trouble happens  when I set the option "**Use image from**" as  "**Imported File**" the variable in the labeling config is converted to "$undefined$",  the problem at least for me and I will be glad if you tell me how correct it, is that I can't find the option to set the variable to aim to the url of the image previusly charged in way to prevent that $undefined$ value. 


```
<View>
  <Image name="image" value="$undefined$"/>

  <Labels name="label" toName="image">
    <Label value="Text" background="green"/>
    <Label value="Handwriting" background="blue"/>
  </Labels>

  <Rectangle name="bbox" toName="image" strokeWidth="3"/>
  <Polygon name="poly" toName="image" strokeWidth="3"/>

  <TextArea name="transcription" toName="image" editable="true" perRegion="true" required="true" maxSubmissions="1" rows="5" placeholder="Recognized Text" displayMode="region-list"/>
</View>
```

**Comment by lazarofrancoe** [comment]
I had the same issue. I fixed it going to Settings -> Labelling Interface -> Use image from <set manually> : **$url** (a literal)

**Comment by jenniferlianne** [comment]
I got this using images imported from Google Cloud, fixed with @lazarofrancoe 's suggestion.

**Comment by makseq** [comment]
`$undefined$` is a system name for LS. Never use it in your labeling configs. 
`$url` or `$image` are correct values. 

**Some points about $undefined$** 

When you import your images/audio/text/csv/other media resources and when you haven't yet set labeling interface, LS know  nothing about what the value name to use. So, LS creates tasks with `$undefined$` value by default, .e.g.:

```
task = {
  "data": {
    "$undefined$": "https://path.com/image.jpg"
  }
}
```

When you specify a labeling config with `<Image value="$url">` and when you import new media files, LS starts using it by default and your tasks will look like this: 

```
task = {
  "data": {
    "url": "https://path.com/image.jpg"
  }
}
```

The key `$undefined$` will be resolved automatically to your labeling config Image value on the fly since your set the labeling config.

**Comment by tgwasira** [comment]
In my case, I was trying to access data from Google Cloud Storage from an application on an http server on my Google Cloud virtual machine. I configured CORS as using the example configuration in the Label Studio documentation, but the requests were still getting blocked. So eventually, I tried this CORS configuration:
```
[
  {
    "origin": ["*"],
    "method": ["*"],
    "responseHeader": ["*"],
    "maxAgeSeconds": 3600
  }
]
```

and it works. This does completely remove all CORS but until I figure out what exactly is needed, I'll be using this.
